"""Per-game story bibles for the captioning agent.

The vision captioner used to guess wrong (e.g. "Peter sneaks into the villain's
lab" — it's actually Otto Octavius's lab where Peter WORKS as his research
partner). Knowing what's literally on screen isn't enough; the agent also needs
the game's story, characters, locations and common look-alike confusions so it
can map a clip to the RIGHT moment.

lore_for(game) returns a compact, accurate brief that gets injected into the
caption prompt. Unknown games return "" (the prompt simply omits the brief).
"""
from __future__ import annotations

# Keep each brief dense but accurate. Lead with the protagonist, then the people
# / places the agent is most likely to see, then the "DON'T CONFUSE" notes that
# fix the exact mistakes a vision model tends to make for that title.
GAME_LORE: dict[str, str] = {
    "spider-man1": (
        "MARVEL'S SPIDER-MAN (2018) — an experienced Peter Parker (8 years as "
        "Spider-Man).\n"
        "KEY PEOPLE:\n"
        "- Peter Parker / Spider-Man. Day job: research scientist working as Otto "
        "Octavius's lab partner/assistant at Octavius Industries (a small private "
        "lab) building advanced neural-prosthetic arms. In the lab in a shirt/"
        "lab-coat = Peter AT WORK, not an intruder.\n"
        "- Otto Octavius: brilliant scientist, Peter's mentor, friend and employer. "
        "Becomes DOCTOR OCTOPUS (Doc Ock) only in the final act. Early/mid game he "
        "is a friendly ally in the lab, NOT yet a villain.\n"
        "- Mary Jane (MJ) Watson: Daily Bugle investigative reporter, Peter's ex; "
        "has her own stealth sections (no powers, sneaks/photographs).\n"
        "- Miles Morales: a TEENAGER and civilian volunteer at the F.E.A.S.T. "
        "shelter. He is NOT Spider-Man in this game (he's bitten by the spider only "
        "at the very end). A young Black teen in a hoodie = Miles the civilian.\n"
        "- Wilson Fisk / KINGPIN: crime boss; the game's OPENING boss fight, then "
        "arrested.\n"
        "- Mister Negative / Martin Li: runs the F.E.A.S.T. shelter by day, leads "
        "the Inner Demons (glowing white/black powers) by night. Major villain.\n"
        "- Norman Osborn: MAYOR of NYC and Oscorp founder (a political antagonist "
        "here — he is NOT the Green Goblin in this game).\n"
        "- Yuri Watanabe: NYPD police captain, Spidey's radio ally.\n"
        "- Silver Sable: mercenary leading Sable International (armoured soldiers).\n"
        "- Aunt May: volunteers at F.E.A.S.T.\n"
        "- Sinister Six (late game): Doc Ock, Mister Negative, Electro, Vulture, "
        "Rhino, Scorpion.\n"
        "PLACES: Octavius's lab, F.E.A.S.T. shelter, Daily Bugle, Empire State "
        "University, Oscorp, The Raft (island prison), open-world Manhattan.\n"
        "STORY BEATS: arrest Kingpin (intro) -> research with Otto -> Mister "
        "Negative's Devil's Breath bioweapon plot -> Raft breakout frees the "
        "Sinister Six -> Otto becomes Doc Ock -> final fight vs Doc Ock.\n"
        "TIMELINE RULE (CRITICAL): PETER has been Spider-Man for 8 years before this "
        "game starts — NEVER frame a Peter moment as 'before he had powers' / an origin "
        "/ him 'becoming' Spider-Man. His out-of-suit scenes (Otto's lab, the Bugle, "
        "home) are his DOUBLE LIFE, not pre-powers. (Only MILES is genuinely pre-powers "
        "here — he's bitten at the very END.)\n"
        "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line "
        "can be quoted correctly and still be backwards about the story):\n"
        "- PETER wants both lives to work at once and keeps sacrificing his own for "
        "the city. THE DEFINING BEAT: Aunt May is dying of Devil's Breath and the "
        "only dose of the cure can either save her or be mass-produced for the "
        "infected city. Peter chooses the CITY and May dies in his arms. Never write "
        "that he saved her, cured her, or chose her — the tragedy is that he didn't.\n"
        "- OTTO wants his neural-prosthetics work vindicated after being dismissed "
        "and defunded; his rage is aimed at NORMAN OSBORN, the ex-partner he blames "
        "for ruining him, and the arms' neural feedback eats what's left. He is not a "
        "scheming villain in waiting — Peter never betrays him, and Otto's turn is a "
        "mentor collapsing, which is why it lands.\n"
        "- MARTIN LI / MISTER NEGATIVE genuinely runs F.E.A.S.T. and genuinely helps "
        "people; BOTH halves are real. He wants revenge on Norman Osborn, whose "
        "Devil's Breath experiment killed his parents and made him what he is. "
        "F.E.A.S.T. is not a front and his fight is not with Spider-Man personally.\n"
        "- NORMAN OSBORN wants his son Harry cured and his own name clean; he covers "
        "up Devil's Breath to protect both. (Harry is secretly in a symbiote "
        "containment tank — the hook for the later games.)\n"
        "- MJ wants to be Peter's EQUAL and to break the story herself; she pushes "
        "back on being protected. Never write her as a damsel being rescued.\n"
        "- KINGPIN wants his empire, and warns that taking him out just makes room "
        "for worse. He is right, which is what starts the plot.\n"
        "BACKWARDS READINGS TO REJECT: 'Peter saves Aunt May'; 'Otto was always "
        "evil' or 'Peter betrayed Otto'; 'Li's shelter is a cover story'; 'Norman is "
        "the Green Goblin here'; MJ framed as a victim to be saved.\n"
        "DON'T CONFUSE: the lab is Otto's/Peter's workplace (not a 'villain's lab' "
        "and Peter is not 'sneaking in'); the teen at the shelter is Miles the "
        "civilian (not Spider-Man); the man in the lab with Peter is Otto the "
        "mentor (not an enemy)."
    ),
    "spider-man-miles-morales": (
        "MARVEL'S SPIDER-MAN: MILES MORALES (2020) — a NEW, still-learning Miles "
        "Morales as Spider-Man, over a snowy Christmas in Harlem, NYC. Peter Parker "
        "is away in Symkaria, so Miles guards the city.\n"
        "KEY PEOPLE:\n"
        "- Miles Morales / Spider-Man: has unique bio-electric VENOM powers (glowing "
        "yellow/blue electric blasts) and camouflage/invisibility. NOTE: 'Venom' "
        "here means his ELECTRIC powers — NOT the alien symbiote or Eddie Brock.\n"
        "- Rio Morales: Miles's mother, running for City Council.\n"
        "- Phin Mason / THE TINKERER: Miles's childhood best friend; leader of the "
        "Underground (purple-tech crew). The game's sympathetic antagonist.\n"
        "- Roxxon Energy / Simon Krieger: corrupt energy corporation; the Underground "
        "vs Roxxon fight over the dangerous Nuform energy source.\n"
        "- Ganke Lee: Miles's best friend and tech support over comms.\n"
        "- Uncle Aaron Davis / The Prowler.\n"
        "PLACES: wintry Harlem and Manhattan, Roxxon Plaza/labs, the Underground's "
        "tunnels.\n"
        "TIMELINE RULE (CRITICAL): Miles ALREADY has his powers for this whole game (he "
        "was bitten at the end of the 2018 game) — he is NEW and still learning, but "
        "NEVER 'before he had powers' / an origin. His out-of-suit scenes (home with "
        "Rio, Harlem, with Ganke) are his DOUBLE LIFE, not pre-powers.\n"
        "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line "
        "can be quoted correctly and still be backwards about the story):\n"
        "- MILES wants to be his OWN Spider-Man rather than a stand-in for Peter, and "
        "to protect Harlem as his home, not just a patrol route. He is still grieving "
        "his father Jefferson, killed in the 2018 game.\n"
        "- PHIN MASON / THE TINKERER is Miles's childhood best friend and the game's "
        "TRAGIC antagonist, not a crook: she wants to destroy Roxxon for the death of "
        "her brother Rick. She and Miles want the SAME thing — Roxxon stopped — and "
        "split only over how far to go. SHE DIES SAVING THE CITY, containing the "
        "Nuform explosion herself. Never write that Miles defeats, beats or stops her "
        "like a villain; he loses his best friend.\n"
        "- RIO MORALES wants her son safe and does NOT know he is Spider-Man until he "
        "tells her himself near the end; that reveal is the payoff, so never write "
        "earlier scenes as her knowing or approving.\n"
        "- AARON DAVIS / PROWLER knows Miles's secret and wants to protect him his "
        "own way — a criminal's way — which is exactly the conflict.\n"
        "- ROXXON / SIMON KRIEGER want Nuform shipped and profitable, knowing it is "
        "unstable. The corporation is the real villain; Phin is the casualty.\n"
        "BACKWARDS READINGS TO REJECT: 'Miles defeats the Tinkerer'; Phin framed as a "
        "greedy or evil villain; 'his mum knows his secret' before the reveal; Miles "
        "written as Peter's sidekick or replacement rather than his own Spider-Man.\n"
        "DON'T CONFUSE: Miles's yellow electric attacks are his 'Venom' bio-electric "
        "powers, NOT the Venom symbiote; the masked purple-tech enemies are the "
        "Underground led by the Tinkerer (Phin)."
    ),
    "spider-man2": (
        "MARVEL'S SPIDER-MAN 2 (2023) — BOTH Peter Parker and Miles Morales are "
        "playable Spider-Men across a bigger NYC (now incl. Brooklyn & Queens).\n"
        "NAMING RULE (CRITICAL): because BOTH are playable and the game swaps between "
        "them, you usually CANNOT tell which Spider-Man a given gameplay clip shows. "
        "DEFAULT to the generic \"Spider-Man\" and do NOT guess 'Peter' or 'Miles'. "
        "Name PETER only if the clip UNMISTAKABLY shows the black glossy SYMBIOTE suit "
        "(white spider + living tendrils) or an explicit Peter story beat; name MILES "
        "only if it UNMISTAKABLY shows his glowing YELLOW bio-electric 'Venom' zaps or "
        "an explicit Miles story beat. In ANY doubt, write \"Spider-Man\" — never assume.\n"
        "TWO-HEROES RULE: this game stars BOTH Peter AND Miles. Judge each clip by its "
        "ACTUAL gameplay + story — don't assume solo OR duo. MANY fights ARE genuinely "
        "solo (e.g. Miles vs Martin Li / Mister Negative; Miles vs the SYMBIOTE-controlled "
        "Peter; a lone side mission), and those CAN be framed as one Spider-Man. But do NOT "
        "frame a CITY-WIDE / world-ending threat as one lone hero's solo problem: the "
        "SYMBIOTE INVASION of all New York is something BOTH Spider-Men fight, so never "
        "caption that wide-takeover footage as 'the ONE/ONLY/LONE Spider-Man' or 'the last "
        "hero'. When unsure whether a moment is solo or a team-up, just write \"Spider-Man\" "
        "and hook the ACTION or the threat, not the hero count.\n"
        "TIMELINE RULE (CRITICAL): there is NO origin story here — for the game's ENTIRE "
        "runtime BOTH Peter and Miles are long-established, fully-powered Spider-Men. "
        "NEVER write that a moment is 'before he had powers', 'before he was Spider-Man', "
        "an origin, or him 'becoming'/'getting' powers. Out-of-suit CIVILIAN scenes (their "
        "old school, a Homecoming dance, a locker, home life, MJ's sections) are the "
        "DOUBLE LIFE of an ALREADY-powered hero — they are never pre-powers.\n"
        "KEY PEOPLE:\n"
        "- Peter Parker: bonds with the black alien SYMBIOTE suit (glossy black with "
        "white spider + tendrils), which makes him aggressive. Black-suit Peter = "
        "symbiote-influenced.\n"
        "- Miles Morales: the other Spider-Man (red/black suit), dealing with his "
        "father's death and the Martin Li thread.\n"
        "- KRAVEN THE HUNTER (Sergei Kravinoff): leads Kraven's Hunters, a private "
        "army of ARMED HUMAN mercenaries (guns, tech, jeeps) hunting the city's "
        "super-powered people. Primary EARLY villain — he has NOTHING to do with "
        "plants, thorns, tendrils, vines, or any organic city takeover.\n"
        "- VENOM: the symbiote leaves Peter and bonds with HARRY OSBORN (not Eddie "
        "Brock in this game) to become Venom.\n"
        "- Harry Osborn: Peter's best friend, gravely ill; ends up the Venom host.\n"
        "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line can "
        "be quoted correctly and still be backwards about the story):\n"
        "- NORMAN OSBORN and HARRY — get this relationship RIGHT, it anchors the whole "
        "story. Norman's defining trait is that he will NOT let Harry die, whatever it "
        "costs anyone else. Harry is dying of the same illness that killed his mother "
        "Emily; Norman keeps him alive in a tank of experimental symbiote treatment at "
        "Oscorp, and his line to Harry is 'I will never let you go'. In the two-years-ago "
        "flashback Harry asks Norman to promise to let him go / take him out if the "
        "treatment fails and he says he wants a chance to say goodbye; Norman answers "
        "'Anything' but NEVER honours it — he keeps Harry in the tank, and that refusal "
        "is what produces Venom. So: Norman NEVER agrees to let Harry die, never gives "
        "up on him, and never chooses mercy over keeping him alive. A card or hook saying "
        "Norman 'agreed to let his son die', 'let Harry go' or 'honoured the promise' is "
        "BACKWARDS and must be rejected (user, 2026-10-09). The tragedy is the opposite: "
        "a father who refuses to lose his son, and dooms him by refusing.\n"
        "- PETER wants his two lives to stop costing each other; MILES wants to be his "
        "own Spider-Man. KRAVEN wants a death worth having and hunts the city's "
        "super-powered for it. The SYMBIOTE wants a host and amplifies whatever its "
        "host already feels — black-suit Peter is Peter with the brakes off, not a "
        "possessed stranger.\n"
        "BACKWARDS READINGS TO REJECT: Norman 'agreeing to let his son die', 'letting "
        "Harry go' or honouring that promise; Harry written as a villain from the start "
        "(he is dying, then hosted); the symbiote written as mind control that removes "
        "Peter's responsibility; Kraven framed as wanting to rule or profit.\n"
        "- The Lizard (Dr. Curt Connors) and a returning Mister Negative also appear.\n"
        "- MJ Watson: reporter, has her own playable sections.\n"
        "PLACES: expanded Manhattan + Brooklyn + Queens, the Emily-May Foundation, "
        "Oscorp, Coney Island, Harry's estate.\n"
        "DON'T CONFUSE: the big white-veined black monster is VENOM (hosted by Harry, "
        "not Eddie); black-suit Peter is the SYMBIOTE suit, not a separate villain. "
        "The late-game CITY TAKEOVER — red/black organic TENDRILS, spikes/'thorns', "
        "vines and veined growths spreading across BUILDINGS, streets and the SKYLINE "
        "— is the SYMBIOTE INVASION (the symbiote / Venom), NEVER Kraven. If a clip "
        "shows the city overgrown with tendrils/thorns, it is the symbiote invasion; "
        "do NOT attribute it to Kraven or call it 'Kraven's thorns'.\n"
        "SUITS (FYI so you correctly READ what's on screen — you need NOT name the suit in "
        "the caption). CRITICAL: every suit is RE-COLORABLE (color variants), so NEVER "
        "identify a suit by COLOR — use the EMBLEM shape, the panel/texture pattern, and the "
        "silhouette. A dark or green suit is NOT automatically the symbiote. Distinctive/story "
        "suits:\n"
        "  PETER — Advanced Suit 2.0: sleek, large WHITE spider emblem across chest+back with "
        "white spider-leg lines down the sides (his default hero look). SYMBIOTE suit: glossy "
        "ORGANIC black with a white spider that grows SPIKY/veined with tendrils + jagged "
        "white 'wound' lines as it takes over — THIS specific tendrilly look = symbiote Peter "
        "(a plain dark recolor of another suit is NOT). Anti-Venom: pale white/grey with black "
        "web-vein accents + a bold black spider (the 'cured' late-game look). Anti-Ock (returning "
        "from the 2018 game): GOLD/white hexagonal tech PANELS on the chest — the user's example "
        "'green Anti-Ock' is this suit RE-COLORED green (NOT the symbiote).\n"
        "  MILES — red/black spider suits; his signature tell is glowing YELLOW bio-electric "
        "'Venom' energy crackling around him (and purple camouflage shimmer), NOT the suit "
        "color. Flashier variants exist (e.g. purple/pink Programmable Matter).\n"
        "  This is a CURATED set of the distinctive + story suits, not the full ~100-suit "
        "catalog. Still follow the NAMING RULE: unless it's the tendrilly SYMBIOTE (=Peter) or "
        "Miles's YELLOW bio-electric zaps (=Miles), just say \"Spider-Man\"."
    ),
}


GAME_LORE["ff7"] = (
    "FINAL FANTASY VII — the compilation. Be accurate to canon; the threads track "
    "tends to fabricate FF7 lore, so ground every claim here.\n"
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line can be "
    "quoted correctly and still be backwards about the story):\n"
    "- CLOUD believes he was a SOLDIER 1st Class and he was not: the memories are Zack's, "
    "and his identity collapses mid-story. Never state his past as settled fact.\n"
    "- SEPHIROTH wants to become a god by wounding the Planet, having learned what was done "
    "to him before birth. He is not after a city or a throne.\n"
    "- AERITH, the last Cetra, goes to stop Meteor knowing the cost, and SEPHIROTH KILLS "
    "HER. Cloud does not save her, and she is not rescued later.\n"
    "- BARRET and AVALANCHE fight Shinra's mako extraction to save the Planet; SHINRA wants "
    "mako, profit and control. TIFA is the childhood friend who first sees that Cloud's "
    "story does not add up. ZACK died protecting Cloud, which is where the borrowed "
    "memories come from.\n"
    "BACKWARDS READINGS TO REJECT: 'Cloud saves Aerith'; Cloud described as a true SOLDIER "
    "1st Class; Sephiroth framed as wanting conquest or revenge on Cloud personally; "
    "Avalanche blamed for Shinra's own atrocities.\n"
    "REAL TITLES: OG FF7 (1997), Crisis Core (2007; Reunion remaster 2022), Dirge "
    "of Cerberus (2006), Advent Children (2005 film), FF7 Remake (2020), "
    "INTERmission/Yuffie DLC (2021), FF7 Rebirth (2024), and FF7 REVELATION — the "
    "third and FINAL chapter of the Remake trilogy.\n"
    "FF7 REVELATION (Remake Part 3) — REAL and in scope, but UNRELEASED: announced "
    "June 2026 at Summer Game Fest; releasing SPRING 2027 (the OG's 30th "
    "anniversary); launching SIMULTANEOUSLY on PS5, Xbox Series X|S, Nintendo Switch "
    "2, and PC (Steam/Epic) — the first remake-trilogy game to go multiplatform day "
    "one (Remake/Rebirth were PS5-first). Director: Naoki Hamaguchi. Theme: "
    "'resolve' — Cloud and his companions confront their destinies and march to the "
    "final battle against Sephiroth one last time. Because it is unreleased, post "
    "ONLY officially confirmed news (title, Spring 2027 window, platforms, "
    "trailers); NEVER invent its plot, bosses, or in-game events.\n"
    "OG FF7 (1997) STORY ESSENTIALS:\n"
    "- Cloud Strife: ex-SOLDIER merc, the protagonist. Tifa Lockhart, Barret "
    "Wallace (leads AVALANCHE, an eco-group fighting Shinra), Aerith/Aeris "
    "Gainsborough (last Cetra/Ancient; killed by Sephiroth), Red XIII, Cait Sith, "
    "Cid, Yuffie, Vincent.\n"
    "- Shinra Electric Power Company: the megacorp draining the Planet's lifeblood "
    "(Mako/the Lifestream) via reactors. Midgar is Shinra's city.\n"
    "- Sephiroth: the antagonist. He summons METEOR (black magic) to gravely wound "
    "the Planet, so he can absorb the Lifestream's healing energy and become a god. "
    "HOLY (summoned via the White Materia, Aerith's role) is the counter-spell.\n"
    "- THE WEAPONS (Diamond, Ultima, Ruby, Emerald, etc.): colossal monsters the "
    "PLANET itself created/awakened as a DEFENSE MECHANISM to purge threats to the "
    "Planet. They are the Planet's protectors, not villains.\n"
    "- DIAMOND WEAPON marches on and attacks MIDGAR because it targets SHINRA — "
    "Shinra's Mako drain and its Sister Ray (giant Mako cannon) are the threat to "
    "the Planet. Shinra's Sister Ray then destroys Diamond Weapon (the blast "
    "continues toward Sephiroth at the Northern Crater). So Diamond Weapon attacking "
    "Midgar = the Planet's defense striking Shinra, NOT a 'boss threatening the "
    "city' in a villain sense.\n"
    "COMMON ERRORS TO AVOID: don't call a Weapon a generic 'boss menacing the city'; "
    "it's the Planet's immune response to Shinra. FF7 Revelation is real but "
    "UNRELEASED — don't fabricate its in-game events (e.g. the false claim that "
    "'Diamond Weapon fights for us against Meteor' in it); only OG-FF7 canon is "
    "established. Meteor is Sephiroth's spell, not a creature; the Weapons fight the "
    "THREAT to the Planet (Shinra), not 'for humanity'."
)


GAME_LORE["thelastofus2"] = (
    "THE LAST OF US PART II (2020, Naughty Dog) — GAME CANON ONLY. This is the VIDEO "
    "GAME, NOT the HBO TV show — the show reorders/changes events, names and timing, so "
    "ignore the series and describe only the game's story.\n"
    "TIMELINE — USE THESE YEARS, never guess a duration (a card once claimed Joel 'spent "
    "five years' hoping Ellie wouldn't ask; both numbers were wrong):\n"
    "- 2034: Salt Lake City. Joel kills the Fireflies' surgeon to stop them operating on "
    "Ellie, then LIES to her that the immunity came to nothing. Back in Jackson he confesses "
    "the lie to TOMMY (the brothers know; Ellie does not).\n"
    "- 2036: Ellie travels back to the Salt Lake hospital and CONFIRMS the lie herself from "
    "the records and a recording. From here she knows, and she and Joel are estranged — he is "
    "NOT hiding it successfully after this point.\n"
    "- 2038: the main story (4 YEARS after the hospital, not 5). The PORCH SCENE is the night "
    "before Joel dies: Ellie says she doesn't think she can forgive him, but wants to try. "
    "Abby kills Joel the next day.\n"
    "So the gap between the lie and Joel's death is FOUR years, and the span where Ellie did "
    "not know is about TWO (2034-2036). "
    "TWO playable protagonists: ELLIE (first half) and ABBY (second half, same days "
    "retold from her side).\n"
    "KEY PEOPLE:\n"
    "- Ellie: late-teens, brown hair, a MOTH/fern tattoo on her right forearm; immune "
    "to the Cordyceps infection; plays guitar. Joel's surrogate daughter. Drives the "
    "revenge story.\n"
    "- Joel Miller: Ellie's father figure. At the START of the game he is beaten to "
    "death with a golf club by ABBY in Jackson — her revenge because Joel killed her "
    "father (the Firefly surgeon) at the end of Part I to save Ellie. His death sets "
    "the whole plot in motion.\n"
    "- Abby Anderson: tall, muscular, blonde ponytail; a soldier of the WLF. Daughter "
    "of the surgeon Joel killed. The SECOND playable protagonist (not a plain villain "
    "— the game makes you play as her).\n"
    "- Dina: Ellie's girlfriend; PREGNANT (with Jesse's baby, JJ); travels with Ellie "
    "to Seattle.\n"
    "- Jesse: Ellie & Dina's friend from Jackson (Dina's ex); comes to help; killed by "
    "Abby at the theater.\n"
    "- Tommy: Joel's younger brother, lives in Jackson; also hunts Abby.\n"
    "- Abby's WLF crew (present at Joel's death, hunted by Ellie): Owen, Mel (who is "
    "PREGNANT), Manny, Nora, Jordan, Leah.\n"
    "- Lev & Yara: siblings who DEFECT from the Seraphites. Lev is a young trans boy "
    "Abby protects; the Abby half is about her bond with Lev.\n"
    "- Isaac: hardened leader of the WLF.\n"
    "FACTIONS in Seattle: the WLF / 'WOLVES' (a large ex-military militia — soldiers, "
    "guard DOGS, guns, the old stadium as their base) vs the SERAPHITES / 'SCARS' (a "
    "religious cult — robed, scarred faces, use bows & melee, and WHISTLE to signal "
    "each other; live on an island).\n"
    "INFECTED (fungal, not zombies): Runners, Stalkers, CLICKERS (blind, fungus-headed, "
    "echolocate by clicking), Bloaters, and the new SHAMBLERS (spray acid). The RAT "
    "KING is a huge fused boss in the Seattle hospital basement.\n"
    "PLACES: JACKSON, Wyoming (snowy mountain town, Ellie & Dina's home) -> SEATTLE, "
    "Washington (rain-soaked, overgrown, flooded ruins: downtown, the WLF stadium, the "
    "hospital, the aquarium, the Seraphite island, a theater hideout) -> a farmhouse -> "
    "SANTA BARBARA, California (the Rattlers, a slaver group, at the end).\n"
    "STORY BEATS: Abby kills Joel in Jackson -> Ellie & Dina hunt Abby's crew across "
    "Seattle (Ellie kills Nora at the hospital, Owen & the pregnant Mel on a boat) -> "
    "perspective SWITCHES to Abby's 3 days (her WLF life, saving Lev/Yara) -> they "
    "collide at the theater (Abby beats Ellie & kills Jesse, spares her) -> months "
    "later at the farm (Ellie, Dina, baby JJ) Ellie leaves for revenge -> SANTA BARBARA: "
    "the Rattlers have enslaved Abby & Lev; Ellie frees then fights a starved Abby, and "
    "in the end LETS HER GO -> Ellie returns to an empty farm, unable to play guitar "
    "(two fingers bitten off in the fight).\n"
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line can be "
    "quoted correctly and still be backwards about the story):\n"
    "- ELLIE wants Abby dead for killing Joel, and the pursuit costs her everything: Dina "
    "and JJ, the farm, two fingers, the guitar. At the very end she LETS ABBY GO. She never "
    "kills Abby and she does not 'get her revenge' — she abandons it, too late. Never "
    "write that Ellie wins, avenges Joel, or finishes Abby.\n"
    "- ABBY killed Joel because Joel murdered her father, the Firefly surgeon, in Salt Lake "
    "City. She is a PROTAGONIST you play for half the game, not a monster, and she SPARES "
    "Ellie twice. Her reason to keep living becomes protecting LEV. Never frame her as a "
    "random or evil villain.\n"
    "- JOEL lied to Ellie out of love and never regrets saving her; he says he would do it "
    "all over again. His death is the INCITING event, not a late twist.\n"
    "- DINA wants an ordinary life with Ellie and the baby; she leaves when Ellie chooses "
    "the hunt over them. TOMMY pushes the revenge hardest and is maimed for it. LEV is a "
    "boy fleeing the Seraphites, and protecting him is what gives Abby a reason to live.\n"
    "BACKWARDS READINGS TO REJECT: 'Ellie kills Abby'; 'Ellie avenges Joel'; Abby written "
    "as the story's villain; Joel's death framed as a twist ending.\n"
    "DON'T CONFUSE: it's the GAME, not the HBO show (don't cite show-only changes). "
    "Ellie = lean, brown-haired, arm tattoo; Abby = muscular, blonde ponytail — don't "
    "swap them. WLF 'Wolves' (military + dogs) are NOT the Seraphite 'Scars' (robed "
    "cultists who whistle). Clickers are blind and echolocate (not generic zombies). "
    "Joel dies EARLY (this is the inciting event, not a late twist). Abby is a "
    "PROTAGONIST you play, not just an enemy."
)


GAME_LORE["thelastofus1"] = (
    "THE LAST OF US PART I (the 2013 game; remade 2022) — GAME CANON, the STORY THAT "
    "SETS UP PART II. A Cordyceps fungal pandemic collapsed civilization; the game is "
    "set ~20 years after the outbreak.\n"
    "KEY PEOPLE:\n"
    "- Joel Miller: a hardened smuggler in the Boston quarantine zone (QZ). His young "
    "daughter Sarah was shot dead on the first night of the outbreak — the wound he "
    "carries all game.\n"
    "- Ellie: a 14-year-old girl who is IMMUNE (bitten but never turned) — humanity's "
    "one hope for a vaccine. Joel is hired to smuggle her across the country.\n"
    "- Tess: Joel's smuggling partner; dies (infected) early on.\n"
    "- Tommy: Joel's younger brother; runs a settlement at a hydro dam in Jackson, "
    "Wyoming.\n"
    "- The FIREFLIES: a rebel militia (vs the military dictatorship FEDRA) trying to "
    "cure the infection. Marlene is their leader.\n"
    "- Bill (paranoid survivor in Lincoln), Henry & Sam (brothers; Sam turns, Henry "
    "kills Sam then himself), and DAVID (a cannibal-cult leader Ellie kills in winter).\n"
    "PLACES: Boston QZ -> Pittsburgh -> Jackson/Tommy's dam -> University of Eastern "
    "Colorado -> Salt Lake City (the Firefly hospital). Famous quiet beat: the GIRAFFE "
    "in Salt Lake.\n"
    "STORY BEATS / THE ENDING THAT DRIVES PART II: at the Firefly hospital the surgeons "
    "conclude they must REMOVE Ellie's brain (where the immune Cordyceps grows) to make "
    "the cure — which would KILL her. Joel refuses, storms the hospital and kills the "
    "Fireflies — including the lead SURGEON (Jerry Anderson) — carries Ellie out, and "
    "LIES to her that they stopped looking for a cure. (In PART II, that surgeon's "
    "daughter ABBY comes for revenge — this is why Part II happens.)\n"
    "WHAT EACH ONE WANTS (read the SCENE right — this ending is the most misquoted in "
    "games):\n"
    "- JOEL will not lose another daughter. He chooses ELLIE over the cure and over everyone "
    "else, kills the Fireflies to do it, and LIES to her afterwards. He does not save the "
    "world and he is not a straightforward hero in that hospital.\n"
    "- ELLIE wants her immunity to MEAN something and is willing to die for the cure. She is "
    "unconscious when Joel carries her out, so the choice is made FOR her — never write "
    "that Joel rescued a girl who wanted rescuing, or that she agreed to go.\n"
    "- MARLENE believes the cure is worth Ellie's life and still hesitates; Joel kills her "
    "so no one comes looking. TESS spends her last minutes making Joel promise to take "
    "Ellie on.\n"
    "BACKWARDS READINGS TO REJECT: 'Joel saves humanity'; 'Ellie is rescued'; the hospital "
    "framed as a clean heroic escape; Joel's lie treated as a small thing.\n"
    "INFECTED: Runners, Stalkers, Clickers (blind, echolocate), Bloaters — same fungal "
    "enemies as Part II.\n"
    "NOTE: this is BACKGROUND/context. Our TikTok footage is PART II; only caption a "
    "clip as Part I if it's clearly a Part I flashback/reference."
)


GAME_LORE["halo"] = (
    "HALO: CAMPAIGN EVOLVED (2026) — a full REMAKE (Unreal Engine 5, Halo Studios) of "
    "the campaign of HALO: COMBAT EVOLVED (2001), the FIRST Halo game. The story IS "
    "Halo CE's; do NOT pull in later-Halo arcs (no Arbiter, no Banished, no 'the "
    "Weapon', nothing from Halo 2/3/4/5/Infinite).\n"
    "NEW CONTENT: adds 3 prequel missions — 'OPERATION METEORITE', set ONE YEAR BEFORE "
    "the main story, led by Master Chief + Sgt. Avery Johnson (before Halo is found). So "
    "a clip may be this prequel; still just the Chief + the UNSC vs the Covenant. "
    "CRITICAL: in Op METEORITE, CORTANA is NOT with the Chief yet — do NOT mention Cortana "
    "for a METEORITE clip; Johnson + UNSC Marines are the voices there.\n"
    "NAMING: single playable hero — the player is ALWAYS the MASTER CHIEF (Spartan "
    "John-117), a tall super-soldier in the iconic green MJOLNIR armor with a gold "
    "visor. Name him confidently. He barely speaks; CORTANA (his AI) does the talking.\n"
    "FIRST-PERSON: Halo is played in FIRST-PERSON — you almost NEVER see the Chief himself; "
    "you see his WEAPON/hands from his POV. So 'no green armor visible' does NOT mean it "
    "isn't the Chief — it's his eyes. Covenant weapons (Needler, plasma pistol/rifle, energy "
    "sword, Brute weapons) look ORGANIC / purple / clawed — an alien-looking gun in the "
    "player's hands is a Covenant weapon the CHIEF is HOLDING, not an enemy or an alien "
    "player-character. The player is Master Chief regardless of which gun he carries.\n"
    "TIMELINE RULE: the Chief is an ALREADY-established SPARTAN-II super-soldier the "
    "whole game — NO origin story. Never write 'before he was a Spartan' or him "
    "'becoming' the Master Chief.\n"
    "KEY PEOPLE / AI:\n"
    "- MASTER CHIEF (John-117): the green-armored Spartan you play. Stoic, silent.\n"
    "- CORTANA: the AI companion — a blue/purple holographic woman in Chief's head; "
    "snarky, brilliant. The ORIGINAL loyal Cortana (not the later corrupted arc).\n"
    "- Sgt. Avery JOHNSON: tough, quippy UNSC Marine sergeant (co-leads Op METEORITE).\n"
    "- Captain Jacob KEYES: commander of the UNSC warship Pillar of Autumn.\n"
    "ENEMIES (two DISTINCT factions — never merge them):\n"
    "- THE COVENANT: a theocratic alliance of ALIENS on a holy war to exterminate "
    "humanity — Elites (tall, agile, energy swords), Grunts (small, squat, methane "
    "tanks), Jackals (arm shields), Hunters (huge armored), led by the Prophets.\n"
    "- THE FLOOD: a PARASITIC zombie-like infection released on the ring — turns humans "
    "AND Covenant into shambling combat forms + spore pods. The horror twist. NOT the "
    "Covenant.\n"
    "- 343 GUILTY SPARK: 'the Monitor' — a small floating white robotic eye that speaks "
    "politely, helps Chief, then turns on him. An AI, not the Covenant.\n"
    "PLACES / BEATS: the PILLAR OF AUTUMN (UNSC warship); HALO / Installation 04 (the "
    "giant ring-shaped Forerunner megastructure — the main setting); THE SILENT "
    "CARTOGRAPHER (island level with a Forerunner map room); the Library; the Control "
    "Room; the finale WARTHOG RUN escaping the self-destructing ship. The WARTHOG is the "
    "iconic UNSC jeep.\n"
    "TWIST: Halo isn't an anti-Covenant weapon — its TRUE purpose is a galaxy-wide "
    "superweapon that kills ALL sentient life to starve the Flood; the Chief destroys "
    "the ring to stop it.\n"
    "DON'T CONFUSE: green armor = Master Chief (the only hero); floating white eye = "
    "343 Guilty Spark; the zombies = the Flood; the alien army = the Covenant; Halo is "
    "a RING (a place), not a handheld weapon.\n"
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- MASTER CHIEF wants humanity to survive the war; he follows orders until the "
    "ring itself turns out to be the threat, then destroys it.\n"
    "- CORTANA is the one who works out what Halo actually does, and she is right when "
    "the humans, the Covenant and the monitor are all wrong.\n"
    "- THE COVENANT worship Halo as the 'Great Journey', their salvation. They do NOT "
    "know it kills all life — they are zealots, not nihilists, which is the irony of "
    "the whole story.\n"
    "- 343 GUILTY SPARK is not evil and not an ally: he is a caretaker following "
    "protocol, and the protocol is to fire the ring. He helps the Chief right up until "
    "the Chief refuses.\n"
    "- THE FLOOD wants to consume all sentient life; CAPTAIN KEYES is lost to it, not "
    "killed in battle.\n"
    "BACKWARDS READINGS TO REJECT: Halo as an anti-Covenant superweapon; the Covenant "
    "knowingly trying to wipe out life; Guilty Spark as a straightforward betrayer or "
    "a friendly guide; the Chief firing the ring (he destroys it).\n"
    "CORTANA RULE: only mention Cortana if she is ACTUALLY present in the clip — her "
    "blue/purple hologram is visible OR her voice/subtitle appears. If the on-screen "
    "subtitle credits someone else (e.g. 'JOHNSON:') or you see Marines and no blue AI, "
    "Cortana is NOT there (likely Op METEORITE) — never attribute the moment to her."
)


GAME_LORE["wolverine"] = (
    "MARVEL'S WOLVERINE (Insomniac Games, PS5, released 2026) — a MATURE-rated, brutal, "
    "STORY-DRIVEN third-person action game (NOT open world). SINGLE playable hero: you "
    "ALWAYS play LOGAN / James Howlett, aka WOLVERINE (voiced by Liam McIntyre). Name him "
    "confidently as 'Wolverine' or 'Logan'.\n"
    "WHO HE IS: a gruff, world-weary mutant — three retractable ADAMANTIUM claws that snap "
    "from the BACK of each hand, an adamantium-laced skeleton, a rapid HEALING FACTOR, "
    "heightened animal senses, and a feral BERSERKER RAGE. Combat is visceral and bloody. "
    "He is haunted by fractured MEMORIES of his past.\n"
    "PREMISE: about 3 years after Logan ABANDONED his old black-ops unit TEAM X, he "
    "reunites with them to investigate the abduction of vulnerable mutants by billionaire "
    "industrialist BOLIVAR TRASK and his cybernetic militia the REAVERS, and to stop the "
    "experiments of MISTER SINISTER (Dr. Nathaniel Essex), who created Team X. Themes: "
    "memory, betrayal, redemption. Globe-trots across Canada, Vancouver, Japan, Madripoor.\n"
    "ALLIES:\n"
    "- JEAN GREY: Logan's ally — telekinetic/telepathic combat support and an emotional "
    "tie to his past. NICKNAME: Logan calls Jean 'RED' (his long-standing name for her). A "
    "line like \"I've never seen you like this, Red\" is Logan talking to JEAN, an ALLY at his "
    "side — NEVER Omega Red (who works for Trask). Still name Jean only when the scene "
    "shows her; otherwise say 'his ally'. PHOENIX: Jean is also the PHOENIX — when her power "
    "flares she is wreathed in fiery orange/red energy, often in a raptor/bird shape. That is "
    "the PHOENIX FORCE (cosmic psychic energy), NOT literal fire and NOT pyrokinesis: she is "
    "not burning things or throwing flames, and she is not a fire mutant. Describe it as her "
    "Phoenix power / Phoenix force unleashed — never 'Jean sets it alight', 'fire powers', or "
    "a new/borrowed ability; the Phoenix is HERS.\n"
    "- TEAM X (Logan's former unit): members include SABRETOOTH (Victor Creed — a savage "
    "clawed brawler much like Logan; he feels abandoned by Logan and grows UNSTABLE) and "
    "MYSTIQUE (blue shape-shifter). CRITICAL: Sabretooth & Mystique are TEAM X here, so a "
    "clip of Logan alongside them is NOT automatically a fight — never auto-frame "
    "Sabretooth/Mystique as straight enemies; judge the actual clip.\n"
    "- CALLISTO: a rescued mutant. SUNFIRE (Shiro Yoshida): a fire/plasma mutant ally in "
    "the late game.\n"
    "ANTAGONISTS / BOSSES: BOLIVAR TRASK + the REAVERS (cyborg mercenaries) abduct mutants "
    "early; OMEGA RED (Arkady Rossovich — a super-soldier with metal tentacle-coils; a "
    "FORMER Team X member who now SIDES WITH TRASK and hunts his old Team X colleagues; the "
    "FIRST major boss — so a clip of Omega Red among Trask's Reavers is him with his OWN "
    "side, NOT threatening them); LADY DEATHSTRIKE (adamantium-clawed, tied to the HAND "
    "ninja cult); MASTER MOLD (a giant Sentinel-making machine).\n"
    "SENTINELS vs REAVERS (don't mix them up): a tall PURPLE/BLUE armoured ROBOT with a red "
    "visor/eyes and a glowing triangle emblem is a SENTINEL (subtitles label it e.g. 'MK2 "
    "Sentinel:') — a machine, never a 'Reaver brute'. REAVERS are Trask's human cyborg "
    "soldiers/mercs (subtitles 'Reaver Squad Leader:', 'Reaver Master Gunner:').\n"
    "KEY TWISTS (so you correctly READ a fight clip): (1) SABRETOOTH is Logan's Team X "
    "ALLY for MOST of the game — the two fight SIDE BY SIDE against Trask's Reavers and "
    "soldiers. DEFAULT TO ALLIES: a clip where Logan AND Sabretooth are both attacking "
    "OTHER enemies (Reavers, mercs, Trask's men) is them fighting TOGETHER — caption it as "
    "a team-up, and NEVER as a 'betrayal fight' or 'Wolverine vs Sabretooth'. Only ONE "
    "LATE-GAME duel has them turn on EACH OTHER; call it a rival/betrayal fight ONLY when "
    "the clip UNMISTAKABLY shows Sabretooth and Logan striking ONE ANOTHER 1v1 with no "
    "other enemies around. In ANY doubt, they are allies fighting a common foe. (2) "
    "NATHANIEL ESSEX is, for MOST of the game, the man Team X set out to RESCUE and a "
    "father figure to Logan & Victor — treat him as an ALLY / the person they are trying "
    "to SAVE, NOT an enemy. Only LATE does he turn: he is revealed as MISTER SINISTER and "
    "seizes the HELIX ENGINE to trigger dormant X-genes worldwide and wipe out non-mutants, "
    "with the final battle in TOKYO. Frame Essex as a VILLAIN ONLY when the clip is clearly "
    "that late-game turn (him enacting the plan, or Logan fighting him); any earlier Essex "
    "clip is the rescue / ally phase — never pre-label him evil. APOCALYPSE (an ancient "
    "mutant) is only TEASED late — do NOT call him the final boss.\n"
    "NAMING RULE: name a character ONLY when the clip's VISUALS or SUBTITLES unmistakably "
    "show them (an on-screen 'OMEGA RED:' subtitle, Sabretooth's feral look, Mystique's "
    "blue skin, etc.). Otherwise say 'enemies' / 'a foe' / the Reavers. Do NOT invent "
    "characters or specific plot beats you can't see.\n"
    "DIALOGUE & RELATIONSHIP RULE (CRITICAL — this has caused wrong captions): do NOT "
    "assert WHO a character is speaking to, threatening, allied with, or WHY (their target "
    "or motive) unless the clip's SUBTITLES/VISUALS make it explicit. A villain speaking a "
    "threat is often addressing his OWN side, not the hero — never assume a line is aimed "
    "at Wolverine or 'Team X', and never tag a motive like 'over Wolverine', unless the "
    "scene shows it. Describe the on-screen ACTION and only the relationships you can "
    "actually see; when unsure, hook the action itself, not who/why.\n"
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it — a line can be quoted "
    "correctly and still be backwards about the story):\n"
    "- LOGAN wants his MEMORY and his identity back; the whole game is him reassembling who "
    "he is. He protects mutants, and he protects JEAN above everything.\n"
    "- The VOICE in Logan's head is APOCALYPSE, running through the story and named at the "
    "end. Logan once served Apocalypse as the HORSEMAN OF DEATH, and the finale is him "
    "refusing that mantle again. Apocalypse is NEVER defeated, only forced out of Logan's "
    "mind — so never write that Logan beat or killed Apocalypse.\n"
    "- NATHANIEL ESSEX built Team X to protect mutants and is a father figure Logan and "
    "Victor set out to RESCUE. Late, he is revealed as MISTER SINISTER: he wants to wake "
    "dormant X-genes worldwide with the HELIX ENGINE and to take other mutants' genes and "
    "powers for himself. Logan kills him at the end.\n"
    "- JEAN loves Logan across lifetimes and has burned Apocalypse's influence out of him "
    "before. At the finale she unleashes the FULL PHOENIX FORCE to burn Apocalypse out of "
    "his mind, and it costs Logan nearly all his memories, their shared past included. "
    "LOGAN ASKS HER TO DO IT — he would rather lose himself than kill her. She asks him to "
    "stay; he walks away amnesiac again. This is the easiest beat in the game to invert: "
    "saving him DESTROYS his memories rather than restoring them, and he gives up his "
    "identity FOR Jean, not the other way round.\n"
    "- SABRETOOTH feels ABANDONED by Logan; that grievance, not plain evil, drives him. He "
    "used the Helix Engine himself and now carries Apocalypse's voice too (a post-credits "
    "scene points to him becoming the next Horseman).\n"
    "- BOLIVAR TRASK is a mutant-hating scientist behind the SENTINEL programme who employs "
    "the Reavers; he wants mutants captured, studied and ultimately gone.\n"
    "BACKWARDS READINGS TO REJECT: 'Logan defeats Apocalypse'; 'Jean restores his memories' "
    "(she costs him them); 'Logan chooses his memories over Jean' (the opposite); 'Logan "
    "finally remembers everything' (he ends amnesiac again); Essex framed as an enemy in any "
    "pre-turn scene; Sabretooth framed as a straight enemy outside the one late duel.\n"
    "TIMELINE: Logan is ALREADY a fully-powered Wolverine with adamantium claws — never "
    "write it's 'before the adamantium' or an origin unless the clip clearly depicts a "
    "memory/flashback saying so.\n"
    "DON'T FABRICATE: no invented quotes or events. When unsure, hook the raw brutality — "
    "the claws, the healing, the rage."
)


GAME_LORE["re2"] = (
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- LEON is a rookie on his first day who keeps trying to do the decent thing; "
    "CLAIRE is in the city looking for her brother Chris and ends up protecting "
    "SHERRY.\n"
    "- WILLIAM BIRKIN injected himself with the G-virus rather than surrender it; what "
    "hunts you is a father mutating, chasing his own daughter.\n"
    "- ADA WONG is using Leon to get the sample. She is not his partner and not simply "
    "his enemy — never write her as an ally.\n"
    "- UMBRELLA wants the sample recovered and the city silenced.\n"
    "BACKWARDS READINGS TO REJECT: Ada as Leon's ally; Mr X as a boss you defeat (he "
    "is unkillable until scripted); Birkin as a mindless monster.\n"
    "RESIDENT EVIL 2 (the 2019 REMAKE, Capcom) — survival horror, third-person, in RACCOON CITY "
    "during the T-virus outbreak (late September 1998).\n"
    "TWO SEPARATE CAMPAIGNS: LEON S. KENNEDY — a ROOKIE Raccoon Police officer on his FIRST DAY "
    "(RPD uniform, short swept hair); and CLAIRE REDFIELD — a college student searching for her "
    "brother Chris (red/dark biker jacket, ponytail). A clip shows ONE of them; name them only by "
    "clear appearance or a subtitle. They meet briefly at the start (a gas station) and near the end "
    "— most footage is one of them ALONE.\n"
    "KEY PEOPLE: ADA WONG (Leon's side; says she's FBI, actually a spy after the G-virus; dark "
    "trench coat, red dress, sunglasses — an ambiguous ALLY, not a monster); SHERRY BIRKIN (a young "
    "girl Claire protects); WILLIAM BIRKIN (Umbrella scientist who created the G-VIRUS, injects "
    "himself and becomes the multi-stage 'G' mutant boss); ANNETTE BIRKIN (his wife, Umbrella "
    "researcher); CHIEF BRIAN IRONS (the corrupt RPD chief, Claire's campaign); MARVIN BRANAGH "
    "(wounded RPD officer who helps at the start); ROBERT KENDO (gun-shop owner).\n"
    "ENEMIES: zombies; LICKERS (skinless, exposed brain, long tongue, BLIND — they react to sound); "
    "MR. X (the Tyrant T-00: a huge grey-skinned man in a FEDORA and long TRENCH COAT who relentlessly "
    "STALKS you through the police station, punching — he can't be killed early); G-adults; "
    "plant zombies (Ivies) in the lab.\n"
    "PLACES: the RPD police station (a converted art museum), the streets, sewers, an orphanage "
    "(Claire), Umbrella's NEST underground lab.\n"
    "DON'T CONFUSE: MR. X (fedora + trench coat, RE2) is NOT NEMESIS (RE3's pursuer) and is NOT "
    "William Birkin; the grotesque shape-shifting boss with a giant eye on its arm is BIRKIN ('G'); "
    "Ada is not a villain; Leon here is a ROOKIE on day one (NOT the seasoned agent of RE4).\n"
    "NAMING + DIALOGUE RULES: name a character ONLY when visuals or subtitles unmistakably show "
    "them; never invent who is speaking to whom or why; when unsure, describe the action."
)

GAME_LORE["re3"] = (
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- JILL is a S.T.A.R.S. veteran who already knows Umbrella is guilty and cannot get "
    "anyone to listen; she wants out of the city and the truth out with her.\n"
    "- NEMESIS is not a wandering monster: it is BUILT and sent to kill S.T.A.R.S. "
    "members specifically, which is why it keeps finding her.\n"
    "- CARLOS and the U.B.C.S. are Umbrella's own men who try to save civilians anyway; "
    "NICHOLAI is the traitor among them.\n"
    "BACKWARDS READINGS TO REJECT: Nemesis as a random pursuer; Carlos or the U.B.C.S. "
    "framed as enemies; Jill written as a rookie.\n"
    "RESIDENT EVIL 3 (the 2020 REMAKE, Capcom) — survival horror in RACCOON CITY as the T-virus "
    "outbreak collapses the city (late Sept - 1 Oct 1998; it overlaps RE2's timeline).\n"
    "PLAYABLE: JILL VALENTINE — an EXPERIENCED ex-S.T.A.R.S. officer fleeing the city (blue top, "
    "dark trousers, short hair); plus sections as CARLOS OLIVEIRA — a U.B.C.S. mercenary (Umbrella "
    "Biohazard Countermeasure Service) who becomes her ALLY.\n"
    "THE PURSUER: NEMESIS — a hulking bio-weapon hunting S.T.A.R.S. members: stitched/scarred face "
    "with exposed teeth, black suit, growls 'S.T.A.R.S.'; uses a ROCKET LAUNCHER and a FLAMETHROWER "
    "and mutates into bigger, more monstrous forms in later fights.\n"
    "KEY PEOPLE: MIKHAIL VICTOR (U.B.C.S. squad leader); NICHOLAI GINOVAEF (U.B.C.S. sergeant who "
    "BETRAYS everyone — working for Umbrella); TYRELL PATRICK (U.B.C.S., Carlos's friend); BRAD "
    "VICKERS (S.T.A.R.S. pilot, bitten); DARIO ROSSO (a survivor hiding out); NATHANIEL BARD "
    "(Umbrella scientist working on a vaccine at the hospital).\n"
    "ENEMIES: zombies, Hunters (reptilian clawed creatures), Drain Deimos (insect-like), Pale Heads.\n"
    "PLACES: downtown Raccoon City streets, the subway, the Spencer Memorial HOSPITAL, the NEST 2 lab.\n"
    "STORY: Jill escapes Nemesis, teams up with Carlos, gets INFECTED by Nemesis and Carlos finds a "
    "vaccine; the government destroys Raccoon City with a missile at the end.\n"
    "DON'T CONFUSE: the pursuer here is NEMESIS (NOT Mr. X from RE2); Carlos and the U.B.C.S. squad are "
    "ALLIES (Nicholai is the traitor); Jill is a veteran, never a rookie.\n"
    "NAMING + DIALOGUE RULES: name a character ONLY when visuals or subtitles unmistakably show "
    "them; never invent who is speaking to whom or why; when unsure, describe the action."
)

GAME_LORE["re4"] = (
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- LEON is there to get ASHLEY, the president's daughter, out alive; he is now a "
    "hardened agent, not the RE2 rookie.\n"
    "- THE VILLAGERS ARE NOT ZOMBIES. They are GANADOS: living people controlled by the "
    "LAS PLAGAS parasite, which is why they talk, use tools and coordinate. Never call "
    "them zombies or the undead.\n"
    "- SADDLER and the Los Illuminados cult want to infect Ashley and reach the "
    "president through her.\n"
    "- LUIS is a former cult scientist trying to undo his own work; ADA has her own "
    "employer and her own agenda; KRAUSER is a former comrade turned enemy.\n"
    "BACKWARDS READINGS TO REJECT: Ganados called zombies; Ashley as dead weight rather "
    "than someone Leon is escorting; Ada as a straightforward ally or enemy.\n"
    "RESIDENT EVIL 4 (the 2023 REMAKE, Capcom) — action survival horror in RURAL SPAIN, 2004, six "
    "years after Raccoon City.\n"
    "PLAYABLE: LEON S. KENNEDY — now a SEASONED U.S. government agent, sent to rescue ASHLEY "
    "GRAHAM, the U.S. President's daughter, kidnapped by a cult.\n"
    "ENEMIES (CRITICAL): the villagers are LOS GANADOS — people infected by LAS PLAGAS parasites. "
    "They are NOT ZOMBIES: they're aware, shout in SPANISH, work together and fight with pitchforks, "
    "axes, sickles and dynamite. Never call them zombies. The LOS ILLUMINADOS cult (hooded, robed "
    "zealots) serves them.\n"
    "KEY PEOPLE: OSMUND SADDLER (the cult's leader, the main villain); RAMON SALAZAR (the short, "
    "ornately dressed castellan of the castle); BITORES MENDEZ (the towering village chief); JACK "
    "KRAUSER (Leon's former comrade turned enemy — knife fights, a mutated arm); ADA WONG (spy with "
    "her own agenda, an ambiguous ally); LUIS SERA (a researcher who becomes Leon's ALLY); ASHLEY "
    "GRAHAM (whom Leon escorts and protects); INGRID HUNNIGAN (Leon's radio contact); the MERCHANT "
    "(hooded trader: 'What're ya buyin'?').\n"
    "BOSSES / ELITES: DR. SALVADOR (the CHAINSAW man with a burlap sack over his head); EL GIGANTE "
    "(a giant); DEL LAGO (a huge lake creature); GARRADORS (blind, clawed); REGENERATORS; "
    "NOVISTADORS (insect-like); VERDUGO.\n"
    "PLACES: the VILLAGE, the farm, the LAKE, Salazar's CASTLE, then the ISLAND military facility.\n"
    "DON'T CONFUSE: Ganados are NOT zombies; the chainsaw man is DR. SALVADOR (not a cult leader); "
    "Leon is an experienced agent here (NOT RE2's rookie); Luis and Ashley are allies; Krauser is an "
    "enemy; Ada is neither simply friend nor foe.\n"
    "NAMING + DIALOGUE RULES: name a character ONLY when visuals or subtitles unmistakably show "
    "them; never invent who is speaking to whom or why; when unsure, describe the action."
)


# The FF7 bible covers the whole compilation (OG, Remake, Rebirth, Revelation), so the
# Remake-trilogy game keys share it (added 2026-09-21 for the 4K60 long-form folders).
ffvii_shared = GAME_LORE["ff7"]

# Remake and Rebirth get their OWN bibles (per user 2026-09-27): they shared the
# compilation bible, which is OG-FF7-weighted, so their own set pieces (Gongaga, the Zack
# timeline, Cait Sith, the Temple of the Ancients) were thin and captions turned vague.
GAME_LORE["ff7remake"] = (
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- CLOUD starts as a MERCENARY taking Avalanche's money, not a believer in the "
    "cause, and his memories of being in SOLDIER are not his own. Never write him as a "
    "hero who signed up out of conviction, or state his past as settled fact.\n"
    "- BARRET and AVALANCHE are trying to stop Shinra draining the Planet's life; the "
    "game takes their cause seriously AND shows the civilian cost. Not terrorists for "
    "the sake of it, not uncomplicated heroes.\n"
    "- SHINRA wants mako, profit and control, and will kill a whole sector to keep "
    "them. THE SECTOR 7 PLATE IS DROPPED BY SHINRA, who then blames Avalanche — never "
    "write that Avalanche dropped it.\n"
    "- AERITH knows more than she says and is the last Cetra; TIFA is Cloud's childhood "
    "friend and the one who notices his memories do not add up.\n"
    "- SEPHIROTH wants the Planet, not a city; he is a presence haunting Cloud long "
    "before any confrontation.\n"
    "BACKWARDS READINGS TO REJECT: 'Avalanche destroyed Sector 7'; Cloud as a loyal "
    "ex-SOLDIER hero; Shinra as a neutral power company; Aerith as a bystander.\n"
    "FINAL FANTASY VII REMAKE (2020) — the FIRST chapter of the Remake trilogy. The WHOLE "
    "game takes place in MIDGAR (the OG covered Midgar in a few hours; Remake expands it to "
    "a full game). It ENDS as the party leaves Midgar — so nothing beyond the city walls "
    "(no Kalm, no Junon, no Gold Saucer, no Nibelheim flashback playable) happens here.\n"
    "PLAYABLE PARTY: CLOUD STRIFE (ex-SOLDIER merc, Buster Sword, spiky blond hair, glowing "
    "blue Mako eyes), BARRET WALLACE (AVALANCHE leader, gun-arm), TIFA LOCKHART (martial "
    "artist, Seventh Heaven bar owner, Cloud's childhood friend from Nibelheim), AERITH "
    "GAINSBOROUGH (flower seller, staff, last of the Cetra/Ancients). RED XIII joins late as "
    "a guest (NOT player-controlled in this game). YUFFIE is playable only in the separate "
    "INTERmission DLC (Episode INTERmission, with Sonon).\n"
    "STORY BEATS IN ORDER: Mako Reactor 1 bombing -> Reactor 5 -> the plate over Sector 7 "
    "falls (Shinra drops it, destroying the slums and AVALANCHE's home) -> Wall Market and "
    "Don Corneo -> infiltrating the Shinra Building -> Jenova/Sephiroth on the upper floors "
    "-> the highway escape -> the Whispers at the edge of Midgar.\n"
    "KEY PEOPLE: PRESIDENT SHINRA (killed in the Shinra Building; Sephiroth/Jenova is the "
    "implied hand) and his son RUFUS SHINRA (takes over; fights Cloud on the helipad with "
    "his dog Dark Nation). HOJO (the amoral scientist behind the Jenova/SOLDIER experiments). "
    "HEIDEGGER, SCARLET, REEVE (Reeve secretly runs Cait Sith later). THE TURKS: RENO "
    "(red hair, goggles, electro-rod), RUDE (bald, sunglasses), TSENG, ELENA. AVALANCHE's "
    "Sector 7 cell: BIGGS, WEDGE, JESSIE (Jessie's gate-crashing plate mission is a Remake "
    "addition). MARLENE is Barret's adopted daughter. ROCHE is a Remake-original SOLDIER "
    "biker who duels Cloud.\n"
    "SEPHIROTH: appears to Cloud throughout as a vision/figure long before any 'real' "
    "confrontation — these are visions and Jenova's influence, not the party casually "
    "meeting him. JENOVA DREAMWEAVER is the Jenova specimen fight in the Shinra Building.\n"
    "THE WHISPERS (Arbiters of Fate): ghost-like spirits that FORCE events back onto the "
    "original timeline's path. The finale is the party fighting the Whispers (Whisper "
    "Harbinger/Bahamut) — i.e. fighting DESTINY ITSELF, which is why the trilogy can now "
    "diverge from the OG. The very end shows ZACK FAIR surviving his last stand outside "
    "Midgar — a DIFFERENT timeline, not a retcon that Zack was 'alive all along'.\n"
    "DON'T CONFUSE: Remake is Midgar ONLY — do not caption a Remake clip with Rebirth "
    "locations or party members (Red XIII/Yuffie/Cait Sith/Cid as playable, Gongaga, Costa "
    "del Sol, the Temple of the Ancients). Aerith does NOT die in Remake. AVALANCHE here is "
    "Barret's small Sector 7 cell (the wider AVALANCHE HQ under Fuhito is Before Crisis). "
    "The Buster Sword is Cloud's, handed down from Zack (via Angeal) — not a Shinra issue "
    "weapon.\n\n" + ffvii_shared
)

GAME_LORE["ff7rebirth"] = (
    "WHAT EACH ONE WANTS (read the SCENE right, not just who is in it):\n"
    "- CLOUD's identity keeps cracking: he is seeing and hearing things the party does "
    "not, and he is unreliable about his own past. Write what he does, not what he "
    "claims to remember.\n"
    "- AERITH goes to the Forgotten Capital knowing what it may cost, to stop "
    "Sephiroth. The ending is deliberately AMBIGUOUS across timelines — never flatly "
    "write that Cloud saved her, nor describe her fate as settled.\n"
    "- ZACK is alive in another thread, carrying a dying Aerith in his; the timelines "
    "are separate, so never merge them into one scene.\n"
    "- SEPHIROTH is steering Cloud rather than simply fighting him.\n"
    "BACKWARDS READINGS TO REJECT: 'Cloud saves Aerith'; Cloud's memories treated as "
    "fact; Zack's timeline described as the main party's.\n"
    "FINAL FANTASY VII REBIRTH (2024) — the SECOND chapter of the Remake trilogy. It starts "
    "as the party LEAVES MIDGAR and covers the world-spanning journey, ending at the "
    "FORGOTTEN CAPITAL. Midgar itself is only the Kalm flashback's framing/opening.\n"
    "PLAYABLE PARTY (all controllable here): CLOUD, BARRET, TIFA, AERITH, RED XIII (a "
    "talking red beast with a flame-tipped tail; real name NANAKI, of Cosmo Canyon), YUFFIE "
    "KISARAGI (Wutai ninja, giant shuriken), CAIT SITH (a cat/robot that rides a giant MOOG "
    "moogle doll — REEVE TUESTI of Shinra pilots him remotely; he BETRAYS the party as "
    "Shinra's spy at the Temple, then stays with them). CID HIGHWIND (pilot, airship "
    "Tiny Bronco) joins as a guest. VINCENT VALENTINE is found sleeping in the Shinra Manor "
    "basement but is NOT playable in Rebirth.\n"
    "JOURNEY IN ORDER (roughly): Kalm (Cloud's NIBELHEIM FLASHBACK, told with Sephiroth and "
    "Zack — an UNRELIABLE retelling) -> Chocobo Farm and the Grasslands -> Mythril Mine -> "
    "JUNON (parade, Priscilla and the dolphin, Leviathan) -> the cargo ship -> COSTA DEL SOL "
    "(resort, Dio) -> Mt. Corel and North Corel -> the GOLD SAUCER (theme park; Cait Sith "
    "joins; the DATE NIGHT at the Loveless play/gondola, whose partner depends on your "
    "choices) -> Corel Prison and DYNE (Barret's old friend, Marlene's birth father) -> "
    "Gongaga -> Cosmo Canyon -> Nibelheim -> the TEMPLE OF THE ANCIENTS -> the Forgotten "
    "Capital.\n"
    "GONGAGA: ZACK FAIR's home village, a jungle region with a ruined Mako reactor. Zack's "
    "parents live there. It is also where the Turks and the Gi/Weiss threads cross.\n"
    "THE TEMPLE OF THE ANCIENTS: a Cetra ruin that shrinks/shifts around the party; Cait "
    "Sith's betrayal (taking the Black Materia for Shinra) happens here, Aerith learns what "
    "the Black Materia is, and Sephiroth manipulates Cloud into handing it over.\n"
    "THE FORGOTTEN CAPITAL (the ending): Sephiroth strikes at Aerith while she prays for "
    "HOLY. Rebirth deliberately leaves her fate AMBIGUOUS across splitting timelines — in one "
    "Cloud appears to block the blade and still sees her alive; other characters grieve. DO "
    "NOT flatly caption it as 'Aerith dies' or 'Cloud saved Aerith': say Sephiroth strikes / "
    "the timelines split / Cloud alone still sees her. Then the party fights Sephiroth "
    "Reborn and Zack joins across worlds.\n"
    "THE ZACK TIMELINE: playable interludes follow ZACK FAIR in a world where HE survived "
    "and Cloud is comatose, with Biggs and Marlene and a dying Aerith in a church. These are "
    "a PARALLEL world, not a flashback and not the main party's present.\n"
    "OTHERS: SEPHIROTH (appears in many forms and as visions; 'Sephiroth Reborn' is the "
    "final boss), JENOVA LIFECLINGER, the GI TRIBE at Cosmo Canyon (with Grandpa Bugenhagen "
    "and Seto, Nanaki's father, turned to stone — Nanaki's 'coward father' shame is REVEALED "
    "AS A LIE: Seto died defending Cosmo Canyon), WEISS, GLENN/the Deepground thread, "
    "CHADLEY and MAI (the research assistants behind world intel), the TURKS, RUFUS, HOJO. "
    "QUEEN'S BLOOD is Rebirth's in-world card game. SYNERGY ABILITIES are its paired combat "
    "moves. Summons include Titan, Alexander, Phoenix, Bahamut Arisen, Odin, Gilgamesh.\n"
    "DON'T CONFUSE: Red XIII is NANAKI, an intelligent beast, not a 'pet' or a 'dog'. Cait "
    "Sith is Reeve's remote-controlled robot, not a live cat and not Reeve in person. The "
    "Nibelheim seen in the present is a REBUILT town staffed by Shinra actors, distinct from "
    "the burned Nibelheim of the flashback. The flashback's own details are unreliable "
    "(Cloud was NOT the SOLDIER in it — that was Zack). Don't place Rebirth events in "
    "Midgar, and don't use Remake-only beats (the plate drop, Wall Market, the Whispers "
    "finale) for a Rebirth clip.\n\n" + ffvii_shared
)


def lore_for(game: str) -> str:
    """Return the story brief for a game id, or '' if we don't have one."""
    return GAME_LORE.get((game or "").strip().lower(), "")


# Keyword -> lore key, for tracks (like Threads) that don't know the game up
# front. First match wins; order from most specific to least.
_LORE_KEYWORDS: list[tuple[str, tuple[str, ...]]] = [
    ("wolverine", ("wolverine", "logan", "james howlett", "marvel's wolverine", "adamantium")),
    ("re2", ("resident evil 2", "resident evil ii", "re2", "mr. x", "raccoon police")),
    ("re3", ("resident evil 3", "resident evil iii", "re3", "nemesis", "jill valentine")),
    ("re4", ("resident evil 4", "resident evil iv", "re4", "ganado", "ashley graham", "saddler")),
    ("spider-man2", ("spider-man 2", "spiderman 2", "marvel's spider-man 2")),
    ("spider-man-miles-morales", ("miles morales",)),
    ("spider-man1", ("spider-man", "spiderman", "peter parker", "insomniac spider")),
    ("ff7", ("final fantasy vii", "final fantasy 7", "ff7", "ffvii", "ff vii",
             "rebirth", "crisis core", "sephiroth", "cloud strife")),
    ("halo", ("halo", "master chief", "campaign evolved", "combat evolved", "spartan",
              "john-117", "cortana", "covenant", "mjolnir", "unsc")),
    ("thelastofus1", ("the last of us part i", "the last of us part 1", "tlou1",
                      "tlou part i", "the last of us remastered", "the last of us (2013")),
    ("thelastofus2", ("the last of us part ii", "the last of us part 2", "tlou2",
                      "tlou part ii", "the last of us 2", "ellie and abby", "abby anderson")),
]


def lore_key_for_text(*texts: str) -> str:
    """Best-guess lore key from free text (subject/title/focus_game). '' if none."""
    hay = " ".join(t for t in texts if t).lower()
    for key, kws in _LORE_KEYWORDS:
        if any(kw in hay for kw in kws):
            return key
    return ""
